[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#e10600"
backgroundColor = "#05060a"
secondaryBackgroundColor = "#111827"
textColor = "#f9fafb"
font = "sans serif"
